/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import9 from '../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import10 from '../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import13 from '../../app/library/grid.component';
import * as import14 from './library/grid.component.ngfactory';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/ng_model';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import25 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_componentTypes(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.componentTypes = currValue;
      this._expr_0 = currValue;
    }
  }
  check_selectedComponentType(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.selectedComponentType = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import2.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _SelectControlValueAccessor_28_3:import8.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_28_4:any[];
  _NgModel_28_5:import9.Wrapper_NgModel;
  _NgControl_28_6:any;
  _NgControlStatus_28_7:import10.Wrapper_NgControlStatus;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _vc_30:import11.ViewContainer;
  _TemplateRef_30_5:any;
  _NgFor_30_6:import12.Wrapper_NgFor;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  compView_49:import2.AppView<import13.Grid>;
  _Grid_49_3:import14.Wrapper_Grid;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','page-header'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Creating AOT Friendly Dynamic Components with Angular 2',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Application Code',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n                        ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n                                ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'span',new import3.InlineArray2(2,'class','input-group-btn'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n                                    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Add Dynamic Grid component',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_20,'\n                \n                                ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_20,'select',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._SelectControlValueAccessor_28_3 = new import8.Wrapper_SelectControlValueAccessor(this.renderer,new import15.ElementRef(this._el_28));
    this._NG_VALUE_ACCESSOR_28_4 = [this._SelectControlValueAccessor_28_3.context];
    this._NgModel_28_5 = new import9.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_28_4);
    this._NgControl_28_6 = this._NgModel_28_5.context;
    this._NgControlStatus_28_7 = new import10.Wrapper_NgControlStatus(this._NgControl_28_6);
    this._text_29 = this.renderer.createText(this._el_28,'\n                                    ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._vc_30 = new import11.ViewContainer(30,28,this,this._anchor_30);
    this._TemplateRef_30_5 = new import16.TemplateRef_(this,30,this._anchor_30);
    this._NgFor_30_6 = new import12.Wrapper_NgFor(this._vc_30.vcRef,this._TemplateRef_30_5,this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.ref);
    this._text_31 = this.renderer.createText(this._el_28,'\n                                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n                            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_38,'div',new import3.InlineArray2(2,'class','col-lg-12'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Library Code',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_42,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                            ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'grid-component',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_49 = new import14.View_Grid0(this.viewUtils,this,49,this._el_49);
    this._Grid_49_3 = new import14.Wrapper_Grid();
    this.compView_49.create(this._Grid_49_3.context);
    this._text_50 = this.renderer.createText(this._el_47,'\n                        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._text_53 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._text_54 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_55 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_28));
    this._NgModel_28_5.subscribe(this,this.eventHandler(this.handleEvent_28),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import18.NgFor) && (30 === requestNodeIndex))) { return this._NgFor_30_6.context; }
    if (((token === import19.SelectControlValueAccessor) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._SelectControlValueAccessor_28_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NG_VALUE_ACCESSOR_28_4; }
    if (((token === import21.NgModel) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgModel_28_5.context; }
    if (((token === import22.NgControl) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControl_28_6; }
    if (((token === import23.NgControlStatus) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatus_28_7.context; }
    if (((token === import13.Grid) && (49 === requestNodeIndex))) { return this._Grid_49_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SelectControlValueAccessor_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_1_0:any = this.context.selectedComponentType;
    this._NgModel_28_5.check_model(currVal_28_1_0,throwOnChange,false);
    this._NgModel_28_5.ngDoCheck(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_7.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_30_0_0:any = this.context.componentTypes;
    this._NgFor_30_6.check_ngForOf(currVal_30_0_0,throwOnChange,false);
    this._NgFor_30_6.ngDoCheck(this,this._anchor_30,throwOnChange);
    this._Grid_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    this._vc_30.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_28_7.checkHost(this,this,this._el_28,throwOnChange);
    this.compView_49.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_30.destroyNestedViews();
    this.compView_49.destroy();
    this._NgModel_28_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 30)) { return new View_AppComponent1(this.viewUtils,this,30,this._anchor_30,this._vc_30); }
    return (null as any);
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this._Grid_49_3.context.addDynamicCellComponent(this.context.selectedComponentType)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_28_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.selectedComponentType = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppComponent1 extends import2.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import8.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import24.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import8.Wrapper_NgSelectOption(new import15.ElementRef(this._el_0),this.renderer,(<View_AppComponent0>this.parentView)._SelectControlValueAccessor_28_3.context);
    this._NgSelectMultipleOption_0_4 = new import24.Wrapper_NgSelectMultipleOption(new import15.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import25.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._NgSelectOption_0_3.check_ngValue(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit;
    this._NgSelectMultipleOption_0_4.check_ngValue(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}